name: feature-pipeline
on: [push]
#  workflow_dispatch
  
  #push:
permissions:
    statuses: write
    contents: read
jobs:
  # Job name
  feature-pipeline: 
    if: github.ref_name != 'main'
    uses: RoboshopGit/workflows/.github/workflows/nodejs-feature-pipeline.yaml@main
    with:
      project: 'roboshop'
      component: 'catalogue'
    secrets: inherit
  